[cd]
launch_shell = true

[finder]
preview = true

[naming]
template = '{{.Host}}/{{.Owner}}/{{.Repository}}-{{.Branch}}'

[worktree]
basedir = '~/ghq'


[naming.sanitize_chars]
'/' = '-'
':' = '-'

[ui]
icons = true
tilde_home = true

