######################################################################
## toml
######################################################################
# toml syntax
[[plugins]] 
repo = 'cespare/vim-toml'
on_ft = 'toml'
######################################################################
## typescript
######################################################################
# [[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
    autocmd BufNewFile,BufRead *.tsx :setfiletype typescript
    let g:typescript_indent_disable = 1
    let g:typescript_compiler_binary = ''
    let g:typescript_compiler_options = ''
'''

[[plugins]]
repo = 'idbrii/vim-tagimposter'
hook_add = '''
'''
######################################################################
## Kotlin
######################################################################
[[plugins]]
repo = 'udalov/kotlin-vim'
hook_add = '''
    autocmd FileType kotlin nmap gd  <esc>:LspDefinition<CR>
'''
on_ft = 'kotlin'
######################################################################
## Go
######################################################################
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    autocmd FileType go nmap <leader>gb  <Plug>(go-build)
    autocmd FileType go nmap <leader>gt  <Plug>(go-test)
    autocmd FileType go nmap <leader>tf  <esc>:GoTestFunc<CR>
    autocmd FileType go nmap <leader>fs  <esc>:GoFillStruct<CR>
    autocmd FileType go imap <leader>fs <esc>:GoFillStruct<CR>
    autocmd FileType go nmap <leader>k  <esc>:GoKeyify<CR>
    autocmd FileType go imap <leader>k  <esc>:GoKeyify<CR>
    autocmd FileType go nmap <leader>at  <esc>:GoAddTags<CR>
    autocmd FileType go nmap <leader>rt  <esc>:GoRemoveTags<CR>
    autocmd FileType go nmap <leader>t  <esc>:GoAlternate<CR>
    autocmd FileType go nmap <leader>rn  <esc>:GoRename<CR>
    autocmd FileType go nmap <leader>i  <esc> :GoImports<CR>
    let g:go_def_mapping_enabled = 0
    let g:go_def_mode='godef'
    let g:go_referrers_mode = 'guru'
    let g:go_gocode_propose_source = 0
    let g:go_gopls_enabled = 0
    let g:go_gopls_complete_unimported = 0
    let g:go_gopls_deep_completion = 0
    let g:go_gopls_fuzzy_matching = 0
    let g:go_gopls_staticcheck = 0
    let g:go_gopls_use_placeholders = 0
    let g:go_diagnostics_enabled = 0
'''
on_ft = 'go'
[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'
# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft = 'go'
######################################################################
## python
######################################################################
[[plugins]]
repo =  'python-mode/python-mode'
on_ft = 'python'
